//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEE.HoatDong.SMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrandNames", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BrandNames : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        private System.Nullable<bool> IsADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<bool> IsAD {
            get {
                return this.IsADField;
            }
            set {
                if ((this.IsADField.Equals(value) != true)) {
                    this.IsADField = value;
                    this.RaisePropertyChanged("IsAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Messages", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Messages : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentField;
        
        private System.Nullable<byte> SmsCountField;
        
        private System.Nullable<decimal> PriceField;
        
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SMSGUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<byte> SmsCount {
            get {
                return this.SmsCountField;
            }
            set {
                if ((this.SmsCountField.Equals(value) != true)) {
                    this.SmsCountField = value;
                    this.RaisePropertyChanged("SmsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string TelName {
            get {
                return this.TelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNameField, value) != true)) {
                    this.TelNameField = value;
                    this.RaisePropertyChanged("TelName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string SerName {
            get {
                return this.SerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SerNameField, value) != true)) {
                    this.SerNameField = value;
                    this.RaisePropertyChanged("SerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SMSGUID {
            get {
                return this.SMSGUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.SMSGUIDField, value) != true)) {
                    this.SMSGUIDField = value;
                    this.RaisePropertyChanged("SMSGUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopUpHistory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TopUpHistory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<System.DateTime> TopUpDateField;
        
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        private System.Nullable<bool> ActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> TopUpDate {
            get {
                return this.TopUpDateField;
            }
            set {
                if ((this.TopUpDateField.Equals(value) != true)) {
                    this.TopUpDateField = value;
                    this.RaisePropertyChanged("TopUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSService.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Generating message contract since element name aboutResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/about", ReplyAction="*")]
        BEE.HoatDong.SMSService.aboutResponse about(BEE.HoatDong.SMSService.aboutRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkClient", ReplyAction="*")]
        BEE.HoatDong.SMSService.checkClientResponse checkClient(BEE.HoatDong.SMSService.checkClientRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changePassword", ReplyAction="*")]
        BEE.HoatDong.SMSService.changePasswordResponse changePassword(BEE.HoatDong.SMSService.changePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name SMSGUID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateSMSStatus", ReplyAction="*")]
        BEE.HoatDong.SMSService.updateSMSStatusResponse updateSMSStatus(BEE.HoatDong.SMSService.updateSMSStatusRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSMS", ReplyAction="*")]
        BEE.HoatDong.SMSService.sendSMSResponse sendSMS(BEE.HoatDong.SMSService.sendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/createBrandName", ReplyAction="*")]
        BEE.HoatDong.SMSService.createBrandNameResponse createBrandName(BEE.HoatDong.SMSService.createBrandNameRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/topup", ReplyAction="*")]
        BEE.HoatDong.SMSService.topupResponse topup(BEE.HoatDong.SMSService.topupRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalance", ReplyAction="*")]
        BEE.HoatDong.SMSService.getBalanceResponse getBalance(BEE.HoatDong.SMSService.getBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBrandNames", ReplyAction="*")]
        BEE.HoatDong.SMSService.getBrandNamesResponse getBrandNames(BEE.HoatDong.SMSService.getBrandNamesRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListSMS", ReplyAction="*")]
        BEE.HoatDong.SMSService.getListSMSResponse getListSMS(BEE.HoatDong.SMSService.getListSMSRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListSMSByPage", ReplyAction="*")]
        BEE.HoatDong.SMSService.getListSMSByPageResponse getListSMSByPage(BEE.HoatDong.SMSService.getListSMSByPageRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTopupHistory", ReplyAction="*")]
        BEE.HoatDong.SMSService.getTopupHistoryResponse getTopupHistory(BEE.HoatDong.SMSService.getTopupHistoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="about", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.aboutRequestBody Body;
        
        public aboutRequest() {
        }
        
        public aboutRequest(BEE.HoatDong.SMSService.aboutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class aboutRequestBody {
        
        public aboutRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aboutResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.aboutResponseBody Body;
        
        public aboutResponse() {
        }
        
        public aboutResponse(BEE.HoatDong.SMSService.aboutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class aboutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aboutResult;
        
        public aboutResponseBody() {
        }
        
        public aboutResponseBody(string aboutResult) {
            this.aboutResult = aboutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkClient", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.checkClientRequestBody Body;
        
        public checkClientRequest() {
        }
        
        public checkClientRequest(BEE.HoatDong.SMSService.checkClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        public checkClientRequestBody() {
        }
        
        public checkClientRequestBody(string clientNo, string clientPass) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.checkClientResponseBody Body;
        
        public checkClientResponse() {
        }
        
        public checkClientResponse(BEE.HoatDong.SMSService.checkClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int checkClientResult;
        
        public checkClientResponseBody() {
        }
        
        public checkClientResponseBody(int checkClientResult) {
            this.checkClientResult = checkClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePassword", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.changePasswordRequestBody Body;
        
        public changePasswordRequest() {
        }
        
        public changePasswordRequest(BEE.HoatDong.SMSService.changePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPass;
        
        public changePasswordRequestBody() {
        }
        
        public changePasswordRequestBody(string clientNo, string oldPass, string newPass) {
            this.clientNo = clientNo;
            this.oldPass = oldPass;
            this.newPass = newPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.changePasswordResponseBody Body;
        
        public changePasswordResponse() {
        }
        
        public changePasswordResponse(BEE.HoatDong.SMSService.changePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int changePasswordResult;
        
        public changePasswordResponseBody() {
        }
        
        public changePasswordResponseBody(int changePasswordResult) {
            this.changePasswordResult = changePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateSMSStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateSMSStatus", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.updateSMSStatusRequestBody Body;
        
        public updateSMSStatusRequest() {
        }
        
        public updateSMSStatusRequest(BEE.HoatDong.SMSService.updateSMSStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateSMSStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMSGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string SMSStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ServiceTypeID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string SecureCode;
        
        public updateSMSStatusRequestBody() {
        }
        
        public updateSMSStatusRequestBody(string SMSGUID, string SMSStatus, string ServiceTypeID, string SecureCode) {
            this.SMSGUID = SMSGUID;
            this.SMSStatus = SMSStatus;
            this.ServiceTypeID = ServiceTypeID;
            this.SecureCode = SecureCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateSMSStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateSMSStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.updateSMSStatusResponseBody Body;
        
        public updateSMSStatusResponse() {
        }
        
        public updateSMSStatusResponse(BEE.HoatDong.SMSService.updateSMSStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateSMSStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateSMSStatusResult;
        
        public updateSMSStatusResponseBody() {
        }
        
        public updateSMSStatusResponseBody(string updateSMSStatusResult) {
            this.updateSMSStatusResult = updateSMSStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMS", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.sendSMSRequestBody Body;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(BEE.HoatDong.SMSService.sendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string smsMessage;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsGUID;
        
        public sendSMSRequestBody() {
        }
        
        public sendSMSRequestBody(string clientNo, string clientPass, string phoneNumber, string sender, string smsMessage, string smsGUID) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.phoneNumber = phoneNumber;
            this.sender = sender;
            this.smsMessage = smsMessage;
            this.smsGUID = smsGUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.sendSMSResponseBody Body;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(BEE.HoatDong.SMSService.sendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendSMSResult;
        
        public sendSMSResponseBody() {
        }
        
        public sendSMSResponseBody(int sendSMSResult) {
            this.sendSMSResult = sendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createBrandNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createBrandName", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.createBrandNameRequestBody Body;
        
        public createBrandNameRequest() {
        }
        
        public createBrandNameRequest(BEE.HoatDong.SMSService.createBrandNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createBrandNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sender;
        
        public createBrandNameRequestBody() {
        }
        
        public createBrandNameRequestBody(string clientNo, string clientPass, string sender) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.sender = sender;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class createBrandNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="createBrandNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.createBrandNameResponseBody Body;
        
        public createBrandNameResponse() {
        }
        
        public createBrandNameResponse(BEE.HoatDong.SMSService.createBrandNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class createBrandNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int createBrandNameResult;
        
        public createBrandNameResponseBody() {
        }
        
        public createBrandNameResponseBody(int createBrandNameResult) {
            this.createBrandNameResult = createBrandNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class topupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="topup", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.topupRequestBody Body;
        
        public topupRequest() {
        }
        
        public topupRequest(BEE.HoatDong.SMSService.topupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class topupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string secureCode;
        
        public topupRequestBody() {
        }
        
        public topupRequestBody(string clientNo, string clientPass, decimal amount, string secureCode) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.amount = amount;
            this.secureCode = secureCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class topupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="topupResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.topupResponseBody Body;
        
        public topupResponse() {
        }
        
        public topupResponse(BEE.HoatDong.SMSService.topupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class topupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int topupResult;
        
        public topupResponseBody() {
        }
        
        public topupResponseBody(int topupResult) {
            this.topupResult = topupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBalance", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getBalanceRequestBody Body;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(BEE.HoatDong.SMSService.getBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        public getBalanceRequestBody() {
        }
        
        public getBalanceRequestBody(string clientNo, string clientPass) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getBalanceResponseBody Body;
        
        public getBalanceResponse() {
        }
        
        public getBalanceResponse(BEE.HoatDong.SMSService.getBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal getBalanceResult;
        
        public getBalanceResponseBody() {
        }
        
        public getBalanceResponseBody(decimal getBalanceResult) {
            this.getBalanceResult = getBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBrandNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBrandNames", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getBrandNamesRequestBody Body;
        
        public getBrandNamesRequest() {
        }
        
        public getBrandNamesRequest(BEE.HoatDong.SMSService.getBrandNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBrandNamesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        public getBrandNamesRequestBody() {
        }
        
        public getBrandNamesRequestBody(string clientNo, string clientPass) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBrandNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBrandNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getBrandNamesResponseBody Body;
        
        public getBrandNamesResponse() {
        }
        
        public getBrandNamesResponse(BEE.HoatDong.SMSService.getBrandNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBrandNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BEE.HoatDong.SMSService.BrandNames[] getBrandNamesResult;
        
        public getBrandNamesResponseBody() {
        }
        
        public getBrandNamesResponseBody(BEE.HoatDong.SMSService.BrandNames[] getBrandNamesResult) {
            this.getBrandNamesResult = getBrandNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListSMS", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getListSMSRequestBody Body;
        
        public getListSMSRequest() {
        }
        
        public getListSMSRequest(BEE.HoatDong.SMSService.getListSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime toDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public byte smsStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string key;
        
        public getListSMSRequestBody() {
        }
        
        public getListSMSRequestBody(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate, byte smsStatus, string key) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.fromDate = fromDate;
            this.toDate = toDate;
            this.smsStatus = smsStatus;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getListSMSResponseBody Body;
        
        public getListSMSResponse() {
        }
        
        public getListSMSResponse(BEE.HoatDong.SMSService.getListSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BEE.HoatDong.SMSService.Messages[] getListSMSResult;
        
        public getListSMSResponseBody() {
        }
        
        public getListSMSResponseBody(BEE.HoatDong.SMSService.Messages[] getListSMSResult) {
            this.getListSMSResult = getListSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListSMSByPageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListSMSByPage", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getListSMSByPageRequestBody Body;
        
        public getListSMSByPageRequest() {
        }
        
        public getListSMSByPageRequest(BEE.HoatDong.SMSService.getListSMSByPageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListSMSByPageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime toDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public byte smsStatus;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int take;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int skip;
        
        public getListSMSByPageRequestBody() {
        }
        
        public getListSMSByPageRequestBody(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate, byte smsStatus, int take, int skip) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.fromDate = fromDate;
            this.toDate = toDate;
            this.smsStatus = smsStatus;
            this.take = take;
            this.skip = skip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListSMSByPageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListSMSByPageResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getListSMSByPageResponseBody Body;
        
        public getListSMSByPageResponse() {
        }
        
        public getListSMSByPageResponse(BEE.HoatDong.SMSService.getListSMSByPageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListSMSByPageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BEE.HoatDong.SMSService.Messages[] getListSMSByPageResult;
        
        public getListSMSByPageResponseBody() {
        }
        
        public getListSMSByPageResponseBody(BEE.HoatDong.SMSService.Messages[] getListSMSByPageResult) {
            this.getListSMSByPageResult = getListSMSByPageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTopupHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopupHistory", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getTopupHistoryRequestBody Body;
        
        public getTopupHistoryRequest() {
        }
        
        public getTopupHistoryRequest(BEE.HoatDong.SMSService.getTopupHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTopupHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime toDate;
        
        public getTopupHistoryRequestBody() {
        }
        
        public getTopupHistoryRequestBody(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTopupHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopupHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public BEE.HoatDong.SMSService.getTopupHistoryResponseBody Body;
        
        public getTopupHistoryResponse() {
        }
        
        public getTopupHistoryResponse(BEE.HoatDong.SMSService.getTopupHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTopupHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BEE.HoatDong.SMSService.TopUpHistory[] getTopupHistoryResult;
        
        public getTopupHistoryResponseBody() {
        }
        
        public getTopupHistoryResponseBody(BEE.HoatDong.SMSService.TopUpHistory[] getTopupHistoryResult) {
            this.getTopupHistoryResult = getTopupHistoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : BEE.HoatDong.SMSService.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<BEE.HoatDong.SMSService.ServiceSoap>, BEE.HoatDong.SMSService.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.aboutResponse BEE.HoatDong.SMSService.ServiceSoap.about(BEE.HoatDong.SMSService.aboutRequest request) {
            return base.Channel.about(request);
        }
        
        public string about() {
            BEE.HoatDong.SMSService.aboutRequest inValue = new BEE.HoatDong.SMSService.aboutRequest();
            inValue.Body = new BEE.HoatDong.SMSService.aboutRequestBody();
            BEE.HoatDong.SMSService.aboutResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).about(inValue);
            return retVal.Body.aboutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.checkClientResponse BEE.HoatDong.SMSService.ServiceSoap.checkClient(BEE.HoatDong.SMSService.checkClientRequest request) {
            return base.Channel.checkClient(request);
        }
        
        public int checkClient(string clientNo, string clientPass) {
            BEE.HoatDong.SMSService.checkClientRequest inValue = new BEE.HoatDong.SMSService.checkClientRequest();
            inValue.Body = new BEE.HoatDong.SMSService.checkClientRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            BEE.HoatDong.SMSService.checkClientResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).checkClient(inValue);
            return retVal.Body.checkClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.changePasswordResponse BEE.HoatDong.SMSService.ServiceSoap.changePassword(BEE.HoatDong.SMSService.changePasswordRequest request) {
            return base.Channel.changePassword(request);
        }
        
        public int changePassword(string clientNo, string oldPass, string newPass) {
            BEE.HoatDong.SMSService.changePasswordRequest inValue = new BEE.HoatDong.SMSService.changePasswordRequest();
            inValue.Body = new BEE.HoatDong.SMSService.changePasswordRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.oldPass = oldPass;
            inValue.Body.newPass = newPass;
            BEE.HoatDong.SMSService.changePasswordResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).changePassword(inValue);
            return retVal.Body.changePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.updateSMSStatusResponse BEE.HoatDong.SMSService.ServiceSoap.updateSMSStatus(BEE.HoatDong.SMSService.updateSMSStatusRequest request) {
            return base.Channel.updateSMSStatus(request);
        }
        
        public string updateSMSStatus(string SMSGUID, string SMSStatus, string ServiceTypeID, string SecureCode) {
            BEE.HoatDong.SMSService.updateSMSStatusRequest inValue = new BEE.HoatDong.SMSService.updateSMSStatusRequest();
            inValue.Body = new BEE.HoatDong.SMSService.updateSMSStatusRequestBody();
            inValue.Body.SMSGUID = SMSGUID;
            inValue.Body.SMSStatus = SMSStatus;
            inValue.Body.ServiceTypeID = ServiceTypeID;
            inValue.Body.SecureCode = SecureCode;
            BEE.HoatDong.SMSService.updateSMSStatusResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).updateSMSStatus(inValue);
            return retVal.Body.updateSMSStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.sendSMSResponse BEE.HoatDong.SMSService.ServiceSoap.sendSMS(BEE.HoatDong.SMSService.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public int sendSMS(string clientNo, string clientPass, string phoneNumber, string sender, string smsMessage, string smsGUID) {
            BEE.HoatDong.SMSService.sendSMSRequest inValue = new BEE.HoatDong.SMSService.sendSMSRequest();
            inValue.Body = new BEE.HoatDong.SMSService.sendSMSRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.sender = sender;
            inValue.Body.smsMessage = smsMessage;
            inValue.Body.smsGUID = smsGUID;
            BEE.HoatDong.SMSService.sendSMSResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).sendSMS(inValue);
            return retVal.Body.sendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.createBrandNameResponse BEE.HoatDong.SMSService.ServiceSoap.createBrandName(BEE.HoatDong.SMSService.createBrandNameRequest request) {
            return base.Channel.createBrandName(request);
        }
        
        public int createBrandName(string clientNo, string clientPass, string sender) {
            BEE.HoatDong.SMSService.createBrandNameRequest inValue = new BEE.HoatDong.SMSService.createBrandNameRequest();
            inValue.Body = new BEE.HoatDong.SMSService.createBrandNameRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.sender = sender;
            BEE.HoatDong.SMSService.createBrandNameResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).createBrandName(inValue);
            return retVal.Body.createBrandNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.topupResponse BEE.HoatDong.SMSService.ServiceSoap.topup(BEE.HoatDong.SMSService.topupRequest request) {
            return base.Channel.topup(request);
        }
        
        public int topup(string clientNo, string clientPass, decimal amount, string secureCode) {
            BEE.HoatDong.SMSService.topupRequest inValue = new BEE.HoatDong.SMSService.topupRequest();
            inValue.Body = new BEE.HoatDong.SMSService.topupRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.amount = amount;
            inValue.Body.secureCode = secureCode;
            BEE.HoatDong.SMSService.topupResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).topup(inValue);
            return retVal.Body.topupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.getBalanceResponse BEE.HoatDong.SMSService.ServiceSoap.getBalance(BEE.HoatDong.SMSService.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public decimal getBalance(string clientNo, string clientPass) {
            BEE.HoatDong.SMSService.getBalanceRequest inValue = new BEE.HoatDong.SMSService.getBalanceRequest();
            inValue.Body = new BEE.HoatDong.SMSService.getBalanceRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            BEE.HoatDong.SMSService.getBalanceResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).getBalance(inValue);
            return retVal.Body.getBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.getBrandNamesResponse BEE.HoatDong.SMSService.ServiceSoap.getBrandNames(BEE.HoatDong.SMSService.getBrandNamesRequest request) {
            return base.Channel.getBrandNames(request);
        }
        
        public BEE.HoatDong.SMSService.BrandNames[] getBrandNames(string clientNo, string clientPass) {
            BEE.HoatDong.SMSService.getBrandNamesRequest inValue = new BEE.HoatDong.SMSService.getBrandNamesRequest();
            inValue.Body = new BEE.HoatDong.SMSService.getBrandNamesRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            BEE.HoatDong.SMSService.getBrandNamesResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).getBrandNames(inValue);
            return retVal.Body.getBrandNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.getListSMSResponse BEE.HoatDong.SMSService.ServiceSoap.getListSMS(BEE.HoatDong.SMSService.getListSMSRequest request) {
            return base.Channel.getListSMS(request);
        }
        
        public BEE.HoatDong.SMSService.Messages[] getListSMS(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate, byte smsStatus, string key) {
            BEE.HoatDong.SMSService.getListSMSRequest inValue = new BEE.HoatDong.SMSService.getListSMSRequest();
            inValue.Body = new BEE.HoatDong.SMSService.getListSMSRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.fromDate = fromDate;
            inValue.Body.toDate = toDate;
            inValue.Body.smsStatus = smsStatus;
            inValue.Body.key = key;
            BEE.HoatDong.SMSService.getListSMSResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).getListSMS(inValue);
            return retVal.Body.getListSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.getListSMSByPageResponse BEE.HoatDong.SMSService.ServiceSoap.getListSMSByPage(BEE.HoatDong.SMSService.getListSMSByPageRequest request) {
            return base.Channel.getListSMSByPage(request);
        }
        
        public BEE.HoatDong.SMSService.Messages[] getListSMSByPage(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate, byte smsStatus, int take, int skip) {
            BEE.HoatDong.SMSService.getListSMSByPageRequest inValue = new BEE.HoatDong.SMSService.getListSMSByPageRequest();
            inValue.Body = new BEE.HoatDong.SMSService.getListSMSByPageRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.fromDate = fromDate;
            inValue.Body.toDate = toDate;
            inValue.Body.smsStatus = smsStatus;
            inValue.Body.take = take;
            inValue.Body.skip = skip;
            BEE.HoatDong.SMSService.getListSMSByPageResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).getListSMSByPage(inValue);
            return retVal.Body.getListSMSByPageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BEE.HoatDong.SMSService.getTopupHistoryResponse BEE.HoatDong.SMSService.ServiceSoap.getTopupHistory(BEE.HoatDong.SMSService.getTopupHistoryRequest request) {
            return base.Channel.getTopupHistory(request);
        }
        
        public BEE.HoatDong.SMSService.TopUpHistory[] getTopupHistory(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate) {
            BEE.HoatDong.SMSService.getTopupHistoryRequest inValue = new BEE.HoatDong.SMSService.getTopupHistoryRequest();
            inValue.Body = new BEE.HoatDong.SMSService.getTopupHistoryRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.fromDate = fromDate;
            inValue.Body.toDate = toDate;
            BEE.HoatDong.SMSService.getTopupHistoryResponse retVal = ((BEE.HoatDong.SMSService.ServiceSoap)(this)).getTopupHistory(inValue);
            return retVal.Body.getTopupHistoryResult;
        }
    }
}
